<?php

namespace Training\Bundle\UserNamingBundle\Model;

/**
 * @author Soundwave2142
 */
class ExtendUserNamingType
{
    /**
     * Constructor
     * The real implementation is autogenerated
     */
    public function __construct()
    {
    }
}