services:
  _defaults:
    public: true
  Oro\Bundle\DashboardBundle\Controller\DashboardController:
    class: Training\Bundle\UserNamingBundle\Controller\DashboardController
    calls:
      - [setContainer, ['@Psr\Container\ContainerInterface']]
    tags:
      - { name: container.service_subscriber }