services:
  _defaults:
    public: true
    autowire: true

  # this is override since I get error about service being private (todo: find better way?)
  oro_dashboard.widget_configs:
    class: Oro\Bundle\DashboardBundle\Model\WidgetConfigs
    arguments:
      - '@oro_dashboard.config_provider'
      - '@oro_dashboard.config_resolver'
      - '@doctrine.orm.entity_manager'
      - '@oro_dashboard.widget_config_value.provider'
      - '@translator'
      - '@event_dispatcher'
      - '@oro_dashboard.widget_config_visibility_filter'
      - '@request_stack'

  Oro\Bundle\DashboardBundle\Model\WidgetConfigs:
    alias: 'oro_dashboard.widget_configs'

  # entity name decorator
  Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator:
    decorates: Oro\Bundle\LocaleBundle\Provider\EntityNameProvider
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  Oro\Bundle\LocaleBundle\Provider\EntityNameProvider: '@oro_locale.entity_name_provider'

  # on UserView event
  Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener:
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }