services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Training\Bundle\UserNamingBundle\:
    resource: '../../*'

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Training\Bundle\UserNamingBundle\Controller\:
    resource: '../../Controller'
    tags: ['controller.service_arguments']

  # this is override since I get error about service being private (todo: find better way?)
  oro_dashboard.widget_configs:
    class: Oro\Bundle\DashboardBundle\Model\WidgetConfigs
    arguments:
      - '@oro_dashboard.config_provider'
      - '@oro_dashboard.config_resolver'
      - '@doctrine.orm.entity_manager'
      - '@oro_dashboard.widget_config_value.provider'
      - '@translator'
      - '@event_dispatcher'
      - '@oro_dashboard.widget_config_visibility_filter'
      - '@request_stack'

  Oro\Bundle\DashboardBundle\Model\WidgetConfigs:
    alias: 'oro_dashboard.widget_configs'

  # this is override since I get error about service being private (todo: find better way?)
  oro_dashboard.manager:
    class: Oro\Bundle\DashboardBundle\Model\Manager
    public: true
    arguments:
      - '@oro_dashboard.factory'
      - '@doctrine.orm.entity_manager'
      - '@oro_security.acl_helper'
      - '@security.token_storage'

  Oro\Bundle\DashboardBundle\Model\Manager:
    alias: oro_dashboard.manager

  # entity name decorator
  Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator:
    decorates: Oro\Bundle\LocaleBundle\Provider\EntityNameProvider
    arguments:
      - '@Training\Bundle\UserNamingBundle\Provider\EntityNameProviderDecorator.inner'
    tags:
      - { name: oro_entity.name_provider, priority: -60 }

  Oro\Bundle\LocaleBundle\Provider\EntityNameProvider: '@oro_locale.entity_name_provider'

  # on UserView event
  Training\Bundle\UserNamingBundle\EventListener\UserViewNamingListener:
    tags:
      - { name: kernel.event_listener, event: oro_ui.scroll_data.before.userView, method: onUserView }